package com.drools.example
import javax.swing.JOptionPane
import javax.swing.JFrame
import javax.swing.Icon
import org.kie.api.runtime.*

global JFrame frame

declare enum Answers
    YES("Yes"),
    NO("no"),
    PERSONAL("personal"),
    PROFESSIONAL("proffessional"),
    COSTAR("It's my costar"),
    STALKER("It's my stalker"),
    THERAPIST("It's my terapist");


    value: String;
end

declare enum QuestionSet
    WHAT_KIND_OF_RELATION("What kind of preexisting relationship do you have with this person?"),
    WHO_IS_THIS("Who is this person?"),
    ARE_YOU_CRAZY("Are you crazy?"),
    WHERE_DO_YOU_LIVE("Do you live in either New York or San Francisco"),
    GENERATE_PUBLICITY("Are you just trying to generate publicity and dispel certain rumors?"),
    RESTRAINING_ORDER_INVOLVED("Is there a restraining order involved?"),
    KIDS_BACK("Is this just an attempt to get your kids back?"),
    THE_ONLY_ONE_WHO_LOVES_YOU("When are you gonna realize that I'm the only one who's ever gonna love you?"),
    HEALTH_RISK("Is your health at any serious risk?"),
    JOB_SUCKS("Does your job sucks?"),
    LONELY(How lonely are you?),
    GETTING_HIGH("Do you wanna get high?"),
    LIKE_DRAMA("Do you like drama?"),
    SEX_WITH_OTHER_PEOPLE("Are you done having sex with other people?"),
    HAVING_CHOICE("Do you really have choice in the matter?"),
    ARE_YOU_RELATED("Are you related?"),
    WHERE_DO_YOU_TEACH("Where do you teach?"),
    SEX_WITH_MINOR("Whoa. You're talking about having sex with a minor, right?"),
    BY_BLOOD("By blood?"),
    ARE_THE_PARENTS_STILL_MARIED("Are the parents still marrid?"),
    ARE_YOU_WOODY_ALLEN("Are you Woody Allen?"),
    DID_YOU_GROW_UP_TOGETHER("Did you grow up together, like from childhood?"),
    REALLY_IN_LOVE_OR_DESPERETA("Are you really in love or just desperate?"),
    DO_YOU_LIVE_IN_A_SPARSELY("Do you live in sparsely populated are? Or the South?");












    value: String
end

declare Question
    question: QuestionSet
    answer: String
end


function void askUser(QuestionSet question, KieRuntime krt){
    String[] options = {Answers.YES.getValue(), Answers.NO.getValue()};
    int n = JOptionPane.showOptionDialog(
                (JFrame) krt.getGlobal("frame"),
                question.getValue(),
                "",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                (Icon) null,
                options,
                options[0]
    		);
    Question q = new Question(question, options[n]);
    krt.insert(q);
}

function void askUserWithOtherOptions(QuestionSet question, KieRuntime krt, Answers[] answers){
    String[] options = new String[answers.length];
    for(int i = 0; i < options.length; i++) {
        options[i] = answers[i].getValue();
    }
    int n = JOptionPane.showOptionDialog(
                (JFrame) krt.getGlobal("frame"),
                question.getValue(),
                "",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                (Icon) null,
                options,
                options[0]
    		);
    Question q;
    if(n >= 0) {
        q = new Question(question, options[n]);
    } else {
        q = new Question(question, null);
    }
    System.out.println(q);
    krt.insert(q);
}


rule init0
    when
    then
        askUserWithOtherOptions(QuestionSet.WHAT_KIND_OF_RELATION, kcontext.getKieRuntime(), new Answers[]{
        	Answers.PROFESSIONAL, Answers.PERSONAL
        });
end

rule "1"
    when
       Question: Question(question == QuestionSet.WHAT_KIND_OF_RELATION && answer == Answers.PROFESSIONAL.getValue())
    then
    askUserWithOtherOptions(QuestionSet.WHO_IS_THIS, kcontext.getKieRuntime(), new Answers[]{
    	Answers.COSTAR, Answers.STALKER, Answers.THERAPIST});
end
